--function goodNoteHit(id, direction, noteType, isSustainNote)
--	if not isSustainNote then
--		setProperty('boyfriend.y', getProperty('boyfriend.y') - 2)
--		setProperty('gf.y', getProperty('gf.y') - 2)
--		--setProperty('dad.y', getProperty('dad.y') - 2)
--		setProperty('dad.y', getProperty('dad.y') - 2)
--
--
--	else
--		setProperty('boyfriend.y', getProperty('boyfriend.y') - 3.2)
--		setProperty('gf.y', getProperty('gf.y') - 3.2)
--	--	setProperty('dad.y', getProperty('dad.y') - 1)
--		setProperty('dad.y', getProperty('dad.y') - 3.2)
--
--	end
--end
--
--function opponentNoteHit(id, direction, noteType, isSustainNote)
--	if not isSustainNote then
--		--setProperty('dad.y', getProperty('dad.y') - 2.2)
--	else
--		setProperty('boyfriend.y', getProperty('boyfriend.y') - 3.2)
--		setProperty('gf.y', getProperty('gf.y') - 3.2)
--		--setProperty('dad.y', getProperty('dad.y') - 3.4)
--	end
--end
--
--function onCreatePost()
--	setProperty('cameraSpeed', 3)
--end