name: Enhancement
description: No, i won't add 6K/etc to the engine or winning icons, stop asking for it.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: "*(Before proceeding, please make sure to check the issues page to see if this has already been reported.)*"

  - type: textarea
    attributes:
      label: What feature do you want to get added on the engine?
    validations:
      required: true
